// 
// Decompiled by Procyon v0.5.36
// 

package groovy.text;

import java.lang.ref.WeakReference;
import groovy.lang.Binding;
import java.util.Map;
import java.util.HashMap;
import groovy.lang.Writable;
import groovy.xml.QName;
import org.codehaus.groovy.runtime.InvokerHelper;
import groovy.util.IndentPrinter;
import groovy.util.XmlNodePrinter;
import org.codehaus.groovy.control.CompilationFailedException;
import groovy.lang.Script;
import groovy.util.Node;
import groovy.lang.GroovyRuntimeException;
import java.io.Writer;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.io.IOException;
import java.io.Reader;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;
import groovy.util.XmlParser;
import groovy.lang.GroovyShell;

public class XmlTemplateEngine extends TemplateEngine
{
    private static int counter;
    public static final String DEFAULT_INDENTATION = "  ";
    private final GroovyShell groovyShell;
    private final XmlParser xmlParser;
    private String indentation;
    
    public XmlTemplateEngine() throws SAXException, ParserConfigurationException {
        this("  ", false);
    }
    
    public XmlTemplateEngine(final String indentation, final boolean validating) throws SAXException, ParserConfigurationException {
        this(new XmlParser(validating, true), new GroovyShell());
        this.setIndentation(indentation);
    }
    
    public XmlTemplateEngine(final XmlParser xmlParser, final ClassLoader parentLoader) {
        this(xmlParser, new GroovyShell(parentLoader));
    }
    
    public XmlTemplateEngine(final XmlParser xmlParser, final GroovyShell groovyShell) {
        this.groovyShell = groovyShell;
        this.xmlParser = xmlParser;
        this.setIndentation("  ");
    }
    
    @Override
    public Template createTemplate(final Reader reader) throws CompilationFailedException, ClassNotFoundException, IOException {
        Node root;
        try {
            root = this.xmlParser.parse(reader);
        }
        catch (SAXException e) {
            throw new RuntimeException("Parsing XML source failed.", e);
        }
        if (root == null) {
            throw new IOException("Parsing XML source failed: root node is null.");
        }
        final StringWriter writer = new StringWriter(1024);
        writer.write("/* Generated by XmlTemplateEngine */\n");
        new GspPrinter(new PrintWriter(writer), this.indentation).print(root);
        Script script;
        try {
            script = this.groovyShell.parse(writer.toString(), "XmlTemplateScript" + XmlTemplateEngine.counter++ + ".groovy");
        }
        catch (Exception e2) {
            throw new GroovyRuntimeException("Failed to parse template script (your template may contain an error or be trying to use expressions not currently supported): " + e2.getMessage());
        }
        return new XmlTemplate(script);
    }
    
    public String getIndentation() {
        return this.indentation;
    }
    
    public void setIndentation(String indentation) {
        if (indentation == null) {
            indentation = "  ";
        }
        this.indentation = indentation;
    }
    
    @Override
    public String toString() {
        return "XmlTemplateEngine";
    }
    
    static {
        XmlTemplateEngine.counter = 1;
    }
    
    private static class GspPrinter extends XmlNodePrinter
    {
        public GspPrinter(final PrintWriter out, final String indent) {
            this(new IndentPrinter(out, indent));
        }
        
        public GspPrinter(final IndentPrinter out) {
            super(out, "\\\"");
            this.setQuote("'");
        }
        
        protected void printGroovyTag(final String tag, final String text) {
            if (tag.equals("scriptlet")) {
                this.out.print(text);
                this.out.print("\n");
                return;
            }
            if (tag.equals("expression")) {
                this.printLineBegin();
                this.out.print("${");
                this.out.print(text);
                this.out.print("}");
                this.printLineEnd();
                return;
            }
            throw new RuntimeException("Unsupported 'gsp:' tag named \"" + tag + "\".");
        }
        
        @Override
        protected void printSimpleItem(final Object value) {
            this.printLineBegin();
            this.out.print(this.escapeSpecialChars(InvokerHelper.toString(value)));
            this.printLineEnd();
        }
        
        private String escapeSpecialChars(final String s) {
            final StringBuilder sb = new StringBuilder();
            boolean inGString = false;
            for (int i = 0; i < s.length(); ++i) {
                final char c = s.charAt(i);
                switch (c) {
                    case '$': {
                        sb.append("$");
                        if (i < s.length() - 1 && s.charAt(i + 1) == '{') {
                            inGString = true;
                            break;
                        }
                        break;
                    }
                    case '<': {
                        this.append(sb, c, "&lt;", inGString);
                        break;
                    }
                    case '>': {
                        this.append(sb, c, "&gt;", inGString);
                        break;
                    }
                    case '\"': {
                        this.append(sb, c, "&quot;", inGString);
                        break;
                    }
                    case '\'': {
                        this.append(sb, c, "&apos;", inGString);
                        break;
                    }
                    case '}': {
                        sb.append(c);
                        inGString = false;
                        break;
                    }
                    default: {
                        sb.append(c);
                        break;
                    }
                }
            }
            return sb.toString();
        }
        
        private void append(final StringBuilder sb, final char plainChar, final String xmlString, final boolean inGString) {
            if (inGString) {
                sb.append(plainChar);
            }
            else {
                sb.append(xmlString);
            }
        }
        
        @Override
        protected void printLineBegin() {
            this.out.print("out.print(\"\"\"");
            this.out.printIndent();
        }
        
        @Override
        protected void printLineEnd(final String comment) {
            this.out.print("\\n\"\"\");");
            if (comment != null) {
                this.out.print(" // ");
                this.out.print(comment);
            }
            this.out.print("\n");
        }
        
        @Override
        protected boolean printSpecialNode(final Node node) {
            final Object name = node.name();
            if (name != null && name instanceof QName) {
                final QName qn = (QName)name;
                if (qn.getNamespaceURI().equals("http://groovy.codehaus.org/2005/gsp") || qn.getPrefix().equals("gsp")) {
                    final String s = qn.getLocalPart();
                    if (s.length() == 0) {
                        throw new RuntimeException("No local part after 'gsp:' given in node " + node);
                    }
                    this.printGroovyTag(s, node.text());
                    return true;
                }
            }
            return false;
        }
    }
    
    private static class XmlTemplate implements Template
    {
        private final Script script;
        
        public XmlTemplate(final Script script) {
            this.script = script;
        }
        
        public Writable make() {
            return this.make(new HashMap());
        }
        
        public Writable make(final Map map) {
            if (map == null) {
                throw new IllegalArgumentException("map must not be null");
            }
            return new XmlWritable(this.script, new Binding(map));
        }
    }
    
    private static class XmlWritable implements Writable
    {
        private final Binding binding;
        private final Script script;
        private WeakReference result;
        
        public XmlWritable(final Script script, final Binding binding) {
            this.script = script;
            this.binding = binding;
            this.result = new WeakReference(null);
        }
        
        public Writer writeTo(final Writer out) {
            final Script scriptObject = InvokerHelper.createScript(this.script.getClass(), this.binding);
            final PrintWriter pw = new PrintWriter(out);
            scriptObject.setProperty("out", pw);
            scriptObject.run();
            pw.flush();
            return out;
        }
        
        @Override
        public String toString() {
            if (this.result.get() != null) {
                return this.result.get().toString();
            }
            final String string = this.writeTo(new StringWriter(1024)).toString();
            this.result = new WeakReference((T)string);
            return string;
        }
    }
}
